### ISSUE TITLE
tp5.0 调用类库的时候报Arrays are not allowed in class constants

### ISSUE THREAD

**Issue by lylovexm** [hsliukangle/card-tool#1]
Arrays are not allowed in class constants

**Comment by hsliukangle** [comment]
> Arrays are not allowed in class constants

看看是不是类型传错了

**Comment by hsliukangle** [comment]
> Arrays are not allowed in class constants

或者您贴一下源代码（卡号可忽略），我看看是不是哪里需要修复一下，感谢！

**Comment by hsliukangle** [comment]
> Arrays are not allowed in class constants

不好意思，晚了两周回复您，我帮您查了一下，可能是由于php版本导致的，我在composer.json中限制了，"php": ">=7.0"

**Comment by hsliukangle** [comment]
> Arrays are not allowed in class constants

如果不能升级php版本，您可以修改源码，CardDb::SEARCH_ORDER 是这里的语法导致的BUG

**Comment by lylovexm** [comment]
好的 谢谢
